"""capstack — a leveraged buyout engine."""

from .balance_sheet import (
    BalanceSheetError,
    OpeningBalanceSheet,
    PurchaseAccounting,
    TargetBookBalanceSheet,
    UnbalancedBalanceSheet,
)
from .covenants import (
    Covenant,
    CovenantObservation,
    CovenantReport,
    Direction,
    Measure,
)
from .daycount import DayCount, year_fraction
from .debt import (
    CapitalStructure,
    CircularityNotResolved,
    DebtPeriod,
    DebtSchedule,
    InterestBasis,
    SweepGrid,
    SweepStep,
    Tranche,
    TranchePeriod,
    TrancheKind,
)
from .drivers import Driver
from .events import (
    Draw,
    Recapitalisation,
    RecapitalisationError,
    RecapitalisationOutcome,
)
from .incentive import (
    IncentiveError,
    OptionPool,
    PoolOutcome,
    Ratchet,
    RatchetBand,
    Vesting,
    settle_pool,
)
from .money import Money, allocate_pro_rata, money, quantize, rate, rescale
from .operating import (
    OperatingAssumptions,
    OperatingModel,
    OperatingPeriod,
    TaxResult,
    apply_carryforward,
)
from .outcome import (
    Attribution,
    Distribution,
    ExitValuation,
    Outcome,
    Security,
    SecurityKind,
    SecurityOutcome,
    default_securities,
)
from .periods import Frequency, Period, PeriodGrid
from .sensitivity import (
    Axis,
    Breakeven,
    Case,
    Cell,
    Dimension,
    Grid,
    Metric,
    SensitivityError,
    Unit,
    solve,
)
from .report import Report, Section
from .returns import (
    AmbiguousIRR,
    CashFlow,
    CashFlowStream,
    IRRError,
    NoSignChange,
    cagr,
    irr_periodic,
    moic,
    npv_periodic,
)
from .spec import (
    Deal,
    DealSpecError,
    EquityPlan,
    Funding,
    IncentivePlan,
    SecurityPlan,
    load_deal,
    parse_deal,
)
from .transaction import (
    DebtFunding,
    EntryValuation,
    LineItem,
    SourcesAndUses,
    Transaction,
    UnbalancedTransaction,
)

__version__ = "0.1.0"

__all__ = [
    "AmbiguousIRR",
    "Attribution",
    "Axis",
    "BalanceSheetError",
    "Breakeven",
    "CapitalStructure",
    "Case",
    "CashFlow",
    "CashFlowStream",
    "Cell",
    "CircularityNotResolved",
    "Covenant",
    "CovenantObservation",
    "CovenantReport",
    "DayCount",
    "Deal",
    "DealSpecError",
    "DebtFunding",
    "DebtPeriod",
    "DebtSchedule",
    "Dimension",
    "Direction",
    "Distribution",
    "Draw",
    "Driver",
    "EntryValuation",
    "EquityPlan",
    "ExitValuation",
    "Frequency",
    "Funding",
    "Grid",
    "IRRError",
    "IncentiveError",
    "IncentivePlan",
    "InterestBasis",
    "LineItem",
    "Measure",
    "Metric",
    "Money",
    "NoSignChange",
    "OpeningBalanceSheet",
    "OperatingAssumptions",
    "OperatingModel",
    "OperatingPeriod",
    "OptionPool",
    "Outcome",
    "Period",
    "PeriodGrid",
    "PoolOutcome",
    "PurchaseAccounting",
    "Ratchet",
    "Recapitalisation",
    "RecapitalisationError",
    "RecapitalisationOutcome",
    "RatchetBand",
    "Report",
    "Section",
    "Security",
    "SecurityKind",
    "SecurityOutcome",
    "SecurityPlan",
    "SensitivityError",
    "SourcesAndUses",
    "SweepGrid",
    "SweepStep",
    "TargetBookBalanceSheet",
    "TaxResult",
    "Tranche",
    "TrancheKind",
    "TranchePeriod",
    "Transaction",
    "UnbalancedBalanceSheet",
    "UnbalancedTransaction",
    "Unit",
    "Vesting",
    "__version__",
    "allocate_pro_rata",
    "apply_carryforward",
    "cagr",
    "default_securities",
    "irr_periodic",
    "load_deal",
    "moic",
    "money",
    "npv_periodic",
    "settle_pool",
    "parse_deal",
    "quantize",
    "rate",
    "rescale",
    "solve",
    "year_fraction",
]
