"""capstack — a leveraged buyout engine."""

from .balance_sheet import (
    BalanceSheetError,
    OpeningBalanceSheet,
    PurchaseAccounting,
    TargetBookBalanceSheet,
    UnbalancedBalanceSheet,
)
from .covenants import (
    Covenant,
    CovenantObservation,
    CovenantReport,
    Direction,
    Measure,
)
from .daycount import DayCount, year_fraction
from .debt import (
    CapitalStructure,
    CircularityNotResolved,
    DebtPeriod,
    DebtSchedule,
    InterestBasis,
    SweepGrid,
    SweepStep,
    Tranche,
    TranchePeriod,
    TrancheKind,
)
from .drivers import Driver
from .money import Money, allocate_pro_rata, money, quantize, rate, rescale
from .operating import (
    OperatingAssumptions,
    OperatingModel,
    OperatingPeriod,
    TaxResult,
    apply_carryforward,
)
from .outcome import (
    Attribution,
    ExitValuation,
    Outcome,
    Security,
    SecurityKind,
    SecurityOutcome,
    default_securities,
)
from .periods import Frequency, Period, PeriodGrid
from .returns import (
    AmbiguousIRR,
    CashFlow,
    CashFlowStream,
    IRRError,
    NoSignChange,
    cagr,
    irr_periodic,
    moic,
    npv_periodic,
)
from .spec import (
    Deal,
    DealSpecError,
    EquityPlan,
    Funding,
    SecurityPlan,
    load_deal,
    parse_deal,
)
from .transaction import (
    DebtFunding,
    EntryValuation,
    LineItem,
    SourcesAndUses,
    Transaction,
    UnbalancedTransaction,
)

__version__ = "0.1.0"

__all__ = [
    "AmbiguousIRR",
    "Attribution",
    "BalanceSheetError",
    "CapitalStructure",
    "CashFlow",
    "CashFlowStream",
    "CircularityNotResolved",
    "Covenant",
    "CovenantObservation",
    "CovenantReport",
    "DayCount",
    "Deal",
    "DealSpecError",
    "DebtFunding",
    "DebtPeriod",
    "DebtSchedule",
    "Direction",
    "Driver",
    "EntryValuation",
    "EquityPlan",
    "ExitValuation",
    "Frequency",
    "Funding",
    "IRRError",
    "InterestBasis",
    "LineItem",
    "Measure",
    "Money",
    "NoSignChange",
    "OpeningBalanceSheet",
    "OperatingAssumptions",
    "OperatingModel",
    "OperatingPeriod",
    "Outcome",
    "Period",
    "PeriodGrid",
    "PurchaseAccounting",
    "Security",
    "SecurityKind",
    "SecurityOutcome",
    "SecurityPlan",
    "SourcesAndUses",
    "SweepGrid",
    "SweepStep",
    "TargetBookBalanceSheet",
    "TaxResult",
    "Tranche",
    "TrancheKind",
    "TranchePeriod",
    "Transaction",
    "UnbalancedBalanceSheet",
    "UnbalancedTransaction",
    "allocate_pro_rata",
    "apply_carryforward",
    "cagr",
    "default_securities",
    "irr_periodic",
    "load_deal",
    "moic",
    "money",
    "npv_periodic",
    "parse_deal",
    "quantize",
    "rescale",
    "rate",
    "year_fraction",
    "__version__",
]
